services:
  wov-quest-result:
    image: pihkaal/wov-quest-result:latest
    networks:
      - web
    environment:
      - WOV_CLAN_ID
      - WOV_API_KEY
      - WOV_FETCH_INTERVAL
      - QUEST_REWARDS
      - QUEST_EXCLUDE
      - DISCORD_MENTION
      - DISCORD_REWARDS_GIVER
      - DISCORD_BOT_TOKEN
      - DISCORD_ADMIN_MENTION
      - DISCORD_ADMIN_CHANNEL
    volumes:
      - cache:/app/.cache
    restart: always

networks:
  web:
    external: true

volumes:
  cache:
